package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'VersioningDemo_HttpsGithubComLpekarHexagonTeamCityDemoRefsHeadsMain'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("VersioningDemo_HttpsGithubComLpekarHexagonTeamCityDemoRefsHeadsMain")
    name = "https://github.com/lpekar-hexagon/team-city-demo#refs/heads/main"
    url = "https://github.com/lpekar-hexagon/team-city-demo"
    branch = "refs/heads/main"
    branchSpec = "refs/heads/*"
    authMethod = password {
        userName = "lpekar-hexagon"
        password = "credentialsJSON:43eaff24-2819-489a-be39-69e2fbe5a889"
    }
}))

