package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildFeatures.perfmon
import jetbrains.buildServer.configs.kotlin.buildSteps.powerShell
import jetbrains.buildServer.configs.kotlin.triggers.finishBuildTrigger
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'IsDailyIsCleanIsNightlyParameters_3OnlyNightly'
in the project with id = 'IsDailyIsCleanIsNightlyParameters', and delete the patch script.
*/
create(RelativeId("IsDailyIsCleanIsNightlyParameters"), BuildType({
    id("IsDailyIsCleanIsNightlyParameters_3OnlyNightly")
    name = "3. OnlyNightly"

    vcs {
        root(DslContext.settingsRoot)
    }

    steps {
        powerShell {
            id = "jetbrains_powershell"

            conditions {
                equals("IsNightlyBuild", "true")
            }
            scriptMode = script {
                content = """
                    echo "====================="
                    echo "3. OnlyNightly"
                    echo "====================="
                """.trimIndent()
            }
        }
    }

    triggers {
        finishBuildTrigger {
            buildType = "IsDailyIsCleanIsNightlyParameters_2OnlyClean"
        }
    }

    features {
        perfmon {
        }
    }
}))

