package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildFeatures.perfmon
import jetbrains.buildServer.configs.kotlin.buildSteps.powerShell
import jetbrains.buildServer.configs.kotlin.triggers.finishBuildTrigger
import jetbrains.buildServer.configs.kotlin.triggers.schedule
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'IsDailyIsCleanIsNightlyParameters_1Build'
in the project with id = 'IsDailyIsCleanIsNightlyParameters', and delete the patch script.
*/
create(RelativeId("IsDailyIsCleanIsNightlyParameters"), BuildType({
    id("IsDailyIsCleanIsNightlyParameters_1Build")
    name = "1. Build"

    vcs {
        root(DslContext.settingsRoot)
    }

    steps {
        powerShell {
            name = "Determine Pipeline Mode"
            id = "Determine_Pipeline_Mode"
            scriptMode = script {
                content = """
                    ${'$'}triggeredBy = "%teamcity.build.triggeredBy%"
                    ${'$'}isCleanBuild = "false"
                    ${'$'}isNightlyBuild = "false"
                    
                    # Detect IsCleanBuild from trigger source
                    if (${'$'}triggeredBy -match "Start Clean Build") {
                        ${'$'}isCleanBuild = "true"
                    }
                    
                    # Detect IsNightlyBuild from current time (nightly window = 00:00 to 06:29)
                    ${'$'}now = Get-Date
                    if (${'$'}now.Hour -lt 6 -or (${'$'}now.Hour -eq 6 -and ${'$'}now.Minute -lt 30)) {
                        ${'$'}isNightlyBuild = "true"
                    }
                    
                    # Set TC parameters for this build
                    Write-Host "##teamcity[setParameter name='IsCleanBuild' value='${'$'}isCleanBuild']"
                    Write-Host "##teamcity[setParameter name='IsNightlyBuild' value='${'$'}isNightlyBuild']"
                    
                    # Persist to shared file for downstream builds
                    ${'$'}propsPath = "D:\%system.teamcity.projectName%\pipeline-state.properties"
                    @"
                    IsCleanBuild=${'$'}isCleanBuild
                    IsNightlyBuild=${'$'}isNightlyBuild
                    "@ | Set-Content -Path ${'$'}propsPath -Encoding UTF8
                    
                    Write-Host "Pipeline mode: IsCleanBuild=${'$'}isCleanBuild, IsNightlyBuild=${'$'}isNightlyBuild (triggered by: ${'$'}triggeredBy)"
                """.trimIndent()
            }
        }
        powerShell {
            id = "jetbrains_powershell"
            scriptMode = script {
                content = """
                    echo "====================="
                    echo "1. Build"
                    echo "IsCleanBuild: %IsCleanBuild%"
                    echo "IsNightlyBuild: %IsNightlyBuild%"
                    echo "====================="
                """.trimIndent()
            }
        }
    }

    triggers {
        finishBuildTrigger {
            buildType = "IsDailyIsCleanIsNightlyParameters_StartCleanBuild"
        }
        finishBuildTrigger {
            enabled = false
            buildType = "IsDailyIsCleanIsNightlyParameters_5LastBuild"
        }
        schedule {
            schedulingPolicy = daily {
                hour = 6
                minute = 30
            }
            branchFilter = ""
            triggerBuild = always()
        }
    }

    features {
        perfmon {
        }
    }
}))

