package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildFeatures.perfmon
import jetbrains.buildServer.configs.kotlin.buildSteps.powerShell
import jetbrains.buildServer.configs.kotlin.triggers.finishBuildTrigger
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'IsDailyIsCleanIsNightlyParameters_2OnlyClean'
in the project with id = 'IsDailyIsCleanIsNightlyParameters', and delete the patch script.
*/
create(RelativeId("IsDailyIsCleanIsNightlyParameters"), BuildType({
    id("IsDailyIsCleanIsNightlyParameters_2OnlyClean")
    name = "2. OnlyClean"

    vcs {
        root(DslContext.settingsRoot)
    }

    steps {
        powerShell {
            name = "Parameters"
            id = "Parameters"
            scriptMode = script {
                content = """
                    echo "IsCleanBuild: %IsCleanBuild%"
                    echo "IsNightlyBuild: %IsNightlyBuild%"
                """.trimIndent()
            }
        }
        powerShell {
            id = "jetbrains_powershell"
            scriptMode = script {
                content = """
                    echo "====================="
                    echo "2. OnlyClean"
                    echo "====================="
                """.trimIndent()
            }
        }
        powerShell {
            name = "Read Pipeline State"
            id = "Read_Pipeline_State"
            scriptMode = script {
                content = """
                    ${'$'}propsPath = "D:\%system.teamcity.projectName%\pipeline-state.properties"
                    if (Test-Path ${'$'}propsPath) {
                        Get-Content ${'$'}propsPath | ForEach-Object {
                            ${'$'}key, ${'$'}value = ${'$'}_ -split '=', 2
                            Write-Host "##teamcity[setParameter name='${'$'}key' value='${'$'}value']"
                        }
                    } else {
                        Write-Host "No pipeline-state.properties found, using defaults"
                    }
                """.trimIndent()
            }
        }
    }

    triggers {
        finishBuildTrigger {
            buildType = "IsDailyIsCleanIsNightlyParameters_1Build"
        }
    }

    features {
        perfmon {
        }
    }
}))

