package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildFeatures.perfmon
import jetbrains.buildServer.configs.kotlin.buildSteps.powerShell
import jetbrains.buildServer.configs.kotlin.triggers.finishBuildTrigger
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'IsDailyIsCleanIsNightlyParameters_4MixedDailyCleanNightly'
in the project with id = 'IsDailyIsCleanIsNightlyParameters', and delete the patch script.
*/
create(RelativeId("IsDailyIsCleanIsNightlyParameters"), BuildType({
    id("IsDailyIsCleanIsNightlyParameters_4MixedDailyCleanNightly")
    name = "4. MixedDailyCleanNightly"

    vcs {
        root(DslContext.settingsRoot)
    }

    steps {
        powerShell {
            name = "Read Pipeline State"
            id = "Read_Pipeline_State_2_2"
            scriptMode = script {
                content = """
                    ${'$'}propsPath = "D:\%system.teamcity.projectName%\pipeline-state.properties"
                    if (Test-Path ${'$'}propsPath) {
                        Get-Content ${'$'}propsPath | ForEach-Object {
                            ${'$'}key, ${'$'}value = ${'$'}_ -split '=', 2
                            Write-Host "##teamcity[setParameter name='${'$'}key' value='${'$'}value']"
                        }
                    } else {
                        Write-Host "No pipeline-state.properties found, using defaults"
                    }
                """.trimIndent()
            }
        }
        powerShell {
            name = "Daily"
            id = "Daily"
            scriptMode = script {
                content = """
                    echo "====================="
                    echo "4. Daily"
                    echo "====================="
                """.trimIndent()
            }
        }
        powerShell {
            name = "Clean"
            id = "Clean"
            scriptMode = script {
                content = """
                    echo "====================="
                    echo "4. Clean"
                    echo "====================="
                """.trimIndent()
            }
        }
        powerShell {
            name = "Nighly"
            id = "Nighly"
            scriptMode = script {
                content = """
                    echo "====================="
                    echo "4. Nightly"
                    echo "====================="
                """.trimIndent()
            }
        }
    }

    triggers {
        finishBuildTrigger {
            buildType = "IsDailyIsCleanIsNightlyParameters_3OnlyNightly"
        }
    }

    features {
        perfmon {
        }
    }
}))

