package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildFeatures.perfmon
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'IsDailyIsCleanIsNightlyParameters_PullLatestChangesFromGit'
in the project with id = 'IsDailyIsCleanIsNightlyParameters', and delete the patch script.
*/
create(RelativeId("IsDailyIsCleanIsNightlyParameters"), BuildType({
    id("IsDailyIsCleanIsNightlyParameters_PullLatestChangesFromGit")
    name = "Pull latest changes from Git"

    vcs {
        root(DslContext.settingsRoot)

        checkoutMode = CheckoutMode.ON_AGENT
    }

    features {
        perfmon {
        }
    }

    dependencies {
        snapshot(RelativeId("IsDailyIsCleanIsNightlyParameters_BuildCounter")) {
            reuseBuilds = ReuseBuilds.ANY
        }
    }
}))

