package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildFeatures.perfmon
import jetbrains.buildServer.configs.kotlin.buildSteps.powerShell
import jetbrains.buildServer.configs.kotlin.triggers.finishBuildTrigger
import jetbrains.buildServer.configs.kotlin.triggers.schedule
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'IsDailyIsCleanIsNightlyParameters_1Build'
in the project with id = 'IsDailyIsCleanIsNightlyParameters', and delete the patch script.
*/
create(RelativeId("IsDailyIsCleanIsNightlyParameters"), BuildType({
    id("IsDailyIsCleanIsNightlyParameters_1Build")
    name = "1. Build"

    vcs {
        root(DslContext.settingsRoot)
    }

    steps {
        powerShell {
            id = "jetbrains_powershell"
            scriptMode = script {
                content = """
                    echo "====================="
                    echo "1. Build"
                    echo "IsCleanBuild: %IsCleanBuild%"
                    echo "IsNightlyBuild: %IsNightlyBuild%"
                    echo "====================="
                """.trimIndent()
            }
        }
    }

    triggers {
        finishBuildTrigger {
            buildType = "IsDailyIsCleanIsNightlyParameters_StartCleanBuild"
        }
        finishBuildTrigger {
            enabled = false
            buildType = "IsDailyIsCleanIsNightlyParameters_5LastBuild"

            buildParams {
                checkbox("IsCleanBuild", "false",
                          checked = "true", unchecked = "false")
            }
        }
        schedule {
            schedulingPolicy = daily {
                hour = 6
                minute = 30
            }
            branchFilter = ""
            triggerBuild = always()

            buildParams {
                checkbox("IsCleanBuild", "false",
                          checked = "true", unchecked = "false")
                checkbox("IsNightlyBuild", "false",
                          checked = "true", unchecked = "false")
            }
        }
    }

    features {
        perfmon {
        }
    }
}))

