package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildFeatures.perfmon
import jetbrains.buildServer.configs.kotlin.buildSteps.powerShell
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'IsDailyIsCleanIsNightlyParameters_5LastBuild'
in the project with id = 'IsDailyIsCleanIsNightlyParameters', and delete the patch script.
*/
create(RelativeId("IsDailyIsCleanIsNightlyParameters"), BuildType({
    id("IsDailyIsCleanIsNightlyParameters_5LastBuild")
    name = "5. LastBuild"

    vcs {
        root(DslContext.settingsRoot)
    }

    steps {
        powerShell {
            id = "jetbrains_powershell"
            scriptMode = script {
                content = """
                    echo "====================="
                    echo "5. LastBuild"
                    echo "====================="
                """.trimIndent()
            }
        }
    }

    features {
        perfmon {
        }
    }
}))

